### ISSUE TITLE
Doesn't properly work in Mobile IE

### ISSUE THREAD

**Issue by fabianmarz** [Mottie/visualNav#10]
On scroll, the site lags and jumps sometimes back to the previous container. I had to turn the plugin off. With enabled it's nearly impossible for IE Mobile users to view the page.

Strange behaviour!

**Comment by Mottie** [comment]
Hi @fabianmarz!

Sadly, I do not own any devices that have mobile IE on them.

I would appreciate any help in troubleshooting this problem.

**Comment by NateOwen** [comment]
If you don't set the hash it works well in IE.  Maybe that could be an option?  updatehash = false

base.setHash = function(newHash){
		if (base.winLoc.hash !== newHash){
			if (base.winLoc.replace){
				//base.winLoc.replace(newHash);
			} else {
				// replace not supported by IE8/9... they get full history
				//base.winLoc.hash = newHash;
			}
		}
	};

**Comment by Mottie** [comment]
Hi @NateOwen!

Doesn't setting the [`useHash` option](https://github.com/Mottie/visualNav/wiki/Options#plugin-function-options) to `false` disable the hash?

**Comment by NateOwen** [comment]
You're right except for one spot.  In findLocation it calls base.updateHash() when it should say 

if(o.useHash) base.updateHash();

At least that fixes my problem.

**Comment by Mottie** [comment]
Hopefully this update fixes @fabianmarz's issue? If not I'll reopen this and ummm, wait until I get a mobile IE device - like never?

**Comment by fabianmarz** [comment]
I also have no access to a Windows mobile device and would hardy probably never have :D. But I will check if it works in my next project where I use this awesome plugin!
IE mobile users now have limited access to the nav/scroll behavior, but that's the price you have to pay.
