### ISSUE TITLE
Begin to the top of the page

### ISSUE THREAD

**Issue by Lucaaas** [Mottie/visualNav#8]
Hi !

My fixed nav is : Compétences - Expériences Professionnelles - Formation - Centres d'intérêt.

My issue is that when i'm arriving on my page, it's automatically scrolling on my first class content but i don't want it. I would like there is not a first scrolling automatically.

Thank you very much.

[Capture d e cran 2013-04-17 a 20 03 03](https://f.cloud.github.com/assets/4183995/392884/163b8aaa-a789-11e2-8051-c68a6124faa7.png)

**Comment by sianrd** [comment]
Hey Rob, just wondered whether you managed to fix the page load problem where it is skipping to the visual nav menu? This is where we are getting the issue - http://www.rhubaba.org/site
Thanks in advance

**Comment by Mottie** [comment]
Hi @sianrd!

I didn't for get about you!

I did look at the code this past weekend, and I "sorta" got it working, but I wasn't happy with how it was behaving. I'll try to look at it again this weekend.

**Comment by sianrd** [comment]
THANKS so much, that's great.

**Comment by Mottie** [comment]
Only 2 years... :see_no_evil: 

The `scrollOnInit` option is set to `false` by default, so the page will no longer automatically scroll to the first anchor.

**Comment by sianrd** [comment]
Thanks so much for looking at it. It now works on every page apart from the home page, don't suppose you'd know why that would be do you? Also, it's now got a weird glitch, where it jumps slightly when it reaches the point at which is it scrolling to. I don't know if that's to do with visual nav or something else conflicting on the site. Thanks again for the help, http://www.rhubaba.org/site

**Comment by Mottie** [comment]
Hmm, that site doesn't follow the layout proposed by the documentation. I can't find a "soloSection" class anywhere on the page either.

I'll have to look at this later to figure out why it's jumping.

**Comment by sianrd** [comment]
Thanks so much! I'm pretty sure I have made it conform to the proposed layout now too.
